dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import include
from django.views.generic import TemplateView
from .views.user import (DashboardView, userreject, SignUp, ProfileUpdateView, PasswordUpdateView, ProjectDeleteView,DashboardInfiniteScroll,
                        get_acquaintances, filesizeupdate, save_filesizeupdate, add_userreject, delete_userreject,upload_files,set_zipfile_name,get_batch,get_files_as_zip,get_remaining_space,payment,stripe_config,create_checkout_session,stripe_webhook,SuccessView,CancelledView,payment_history)
from .forms import ProfiledAuthenticationForm,PasswordResetFormUpdate
from django.urls import reverse_lazy

app_name = "dashboard"

urlpatterns = [
    # path('', TemplateView.as_view(template_name="dashboard/home.html"), name="homepage"),
    path('',DashboardView.as_view(), name="homepage"),
    path('home/infinite-scroll/',DashboardInfiniteScroll.as_view(), name="dashboardInfiniteScroll"),  
    path('userreject/', userreject, name="userreject"),
    path('add_userreject/', add_userreject, name="add_userreject"),
    path('delete_userreject/', delete_userreject, name="delete_userreject"),
    path('volumn/', filesizeupdate, name='volumn'),
    path('update_file_size', save_filesizeupdate, name="save_filesizeupdate"),
    path('upload_files',upload_files,name='upload_files'),
    path('set_zipfile_name',set_zipfile_name,name='set_zipfile_name'),
    path('payment',payment,name='payment'),
    path('payment_history',payment_history,name='payment_history'),

    # payment
    path('config/', stripe_config,name='config'),
    path('create-checkout-session/',create_checkout_session),
    path('payment/success/', SuccessView.as_view()),
    path('payment/cancelled/', CancelledView.as_view()),
    path('payment/webhook/', stripe_webhook),

    path('login/', auth_views.LoginView.as_view(form_class=ProfiledAuthenticationForm, redirect_authenticated_user=True), name="login"),
    path('signup/', SignUp.as_view(), name="signup"),
    path('password_change/', PasswordUpdateView.as_view(), name='password_change'),
    path('password-reset/',auth_views.PasswordResetView.as_view(form_class=PasswordResetFormUpdate,success_url=reverse_lazy('dashboard:password_reset_done')),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('dashboard:password_reset_complete')),name='password_reset_confirm'),
    path('password-reset/complete/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name="profile"),

    path('acquaintances/', get_acquaintances, name="acquaintances"),
    path('project/<int:project_id>/delete', ProjectDeleteView.as_view(), name="projectDelete"),
    # path('', include('django.contrib.auth.urls'))
    path('<uuid:batch_id>',get_batch,name='get_batch'),
    path('get_files_as_zip',get_files_as_zip,name='get_files_as_zip'),
    path('get_remaining_space',get_remaining_space,name='get_remaining_space'),
]

techup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from decorator_include import decorator_include
from django.contrib.auth.decorators import login_required


urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('designs/', decorator_include([login_required], ('designs.urls', 'designs'))),
    path('', include('dashboard.urls'))
]

if not settings.PRODUCTION:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.apps import apps
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
# Create your models here.
from django.contrib.auth.models import User
from django.contrib.auth.models import UserManager
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.db.models import Sum
from django.conf import settings
import uuid

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_admin = models.BooleanField(_("Is Admin?"), default=False)
    avatar =  models.ImageField(_("user avatar"), upload_to="user_avatars",blank=True, null=True,default=None)
    file_size = models.IntegerField(default=settings.MAX_UPLOAD_SIZE)

    @property
    def display_name(self):
        name = "ユーザー"
        if self.user.last_name:
            name = self.user.last_name
        if self.user.first_name:
            name += " " + self.user.first_name + "."
        return name

    @property
    def can_login(self):
        return self.user

    @property
    def occupied_space(self):
        all_batch = self.user.batch_set.all().values_list('id',flat=True)
        occupied_space = BatchFile.objects.filter(batch_id__in=all_batch).aggregate(Sum('size'))
        return occupied_space['size__sum']

    @property
    def remaining_space(self):
        occupied = self.occupied_space
        if occupied:
            return (self.user.profile.file_size-occupied)
        else:
            return settings.MAX_UPLOAD_SIZE


class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(_("Project Title"), max_length=256)
    pub_date = models.DateTimeField(_("Date added"),editable=False, auto_now_add=True)

    # class Meta:
    #     ordering = ['id']

class RejectUser(models.Model):
    email = models.EmailField(_('E-mail address'), blank=False)
    applied = models.DateTimeField(auto_now_add=True)

class Batch(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=255,blank=True,null=True)

class BatchFile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    file = models.FileField(upload_to='files',blank=True,null=True,default=None)
    batch = models.ForeignKey(Batch,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    size = models.IntegerField(default=0)


class PaymentHistory(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    storage = models.IntegerField()
    price = models.FloatField(default=0)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile = Profile.objects.create(user=instance)
        profile.save()


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Project,RejectUser
from django.utils.translation import ugettext, ugettext_lazy as _
from django.forms import formset_factory
from django.urls import reverse_lazy
from django.template.loader import render_to_string
from django.template import loader
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from django.conf import settings

from django.contrib.auth.forms import (
    AuthenticationForm,PasswordResetForm,UsernameField
)

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(label="メールアドレス", required=True)
    
    last_name = forms.CharField(label='ユーザーネーム', required=True)
    password1 = forms.CharField(label='パスワード', required=True, strip=False, widget=forms.PasswordInput())
    password2 = forms.CharField(label='パスワード確認', required=True, strip=False, widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ("email", "last_name", "password1", "password2")

    def clean(self):
        super(UserCreateForm, self).clean()
        try:
            try:
                user = RejectUser.objects.get(email=self.cleaned_data['email'])
                raise forms.ValidationError("A user with this E-mail address already was added in rejectuser.")
            except RejectUser.DoesNotExist:
                user = User.objects.get(email=self.cleaned_data['email'])
                raise forms.ValidationError("A user with this E-mail address already exists.")
        except User.DoesNotExist:
            pass

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.username = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["last_name"]
        #user.last_name = self.cleaned_data["first_name"]
        user.save()
        return user

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ("title",)

class ProjectAdminForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ("title", )

class ProfiledAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        label=_("メールアドレス"),
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True,'placeholder': 'メールアドレス'}),
    )
    password = forms.CharField(
        label=_("パスワード"),
        strip=False,
        widget=forms.PasswordInput(attrs={'placeholder': 'パスワード'}),
    )
    #remember_me = forms.BooleanField(required=False,widget=forms.CheckboxInput(attrs={'class':'scalero-checkbox','id':'remember-me'}))
    profile_error_messages = {
        "invalid_profile": _("メールアドレスまたはパスワードが正しくありません。"
        )
    }

    def clean(self):
        super(ProfiledAuthenticationForm, self).clean()
        if self.user_cache:
            if not self.user_cache.profile.can_login:
                raise forms.ValidationError(
                    self.profile_error_messages['invalid_profile'],
                    code='invalid_profile',
                    params={'username': self.username_field.verbose_name},
                )
class PasswordResetFormUpdate(PasswordResetForm):
    email = UsernameField(
        max_length=254,
        widget=forms.TextInput(attrs={'autofocus': True,'placeholder': 'メールアドレス'}),
    )
    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        subject = "パスワード再設定"
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        
        #message = Mail(from_email=settings.EMAIL_FROM,to_emails=to_email,subject=subject,html_content=body)
        url = reverse_lazy('dashboard:password_reset_confirm',kwargs={'uidb64':context['uid'],'token':context['token']})        
        confirm_url = str(context['protocol'])+'://'+str(context['domain'])+str(url)
        html_body = render_to_string("registration/password_reset_email.html", {'url':confirm_url})
        
        message = Mail(
            from_email=settings.EMAIL_FROM,
            to_emails=to_email,
            subject=subject,
            html_content=html_body
        )
        try:
            sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
            response = sg.send(message)
        except Exception as e:
            print(e)

dashboard/views/admin.py
from dashboard.models import User
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponse
import json
from django.contrib.auth.decorators import user_passes_test

from django.views.decorators.http import require_http_methods
from django.urls import reverse_lazy


def is_admin(user):
    return user.profile.is_admin

   

dashboard/templates/dashboard/batch.html
{% extends 'designs/base.html' %}
{% load static %}
{% block links %}
{% endblock %}
{% block content %}
    <div id="content" class="container-fluid auth-wrapper full-height">
        <div class="row flex-1">
            <div class="col-lg-4 col-md-12 justify-content-center auth-panel">
                <div class="card">
                    <div class="card-header">
                        {{ batch.name }}.zip
                    </div>
                    <div class="card-body">
                        <a href="{% url 'dashboard:get_files_as_zip' %}?batch_id={{ batch.id }}" class="btn btn-primary">ダウンロード</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
{% endblock %}

dashboard/templates/dashboard/payment.html
{% extends 'designs/base.html' %}
{% block content %}
{% load static %}
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    </br>
    </br>
        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:homepage' %}">
                <i class="fas fa-fw fa-folder"></i>
                <span>ファイル管理</span></a>
        </li>
        <hr class="sidebar-divider">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'dashboard:payment' %}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>ペイメント</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
    </ul>
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Begin Page Content -->
            <div class="container-fluid">
                <!-- Content Row -->
                <div class="row">
                    <div class=" col-xl-12 col-lg-12">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="card shadow">
                                    <div class="card-header">
                                        <span>パッケージ1</span>
                                    </div>
                                    <div class="card-body">
                                        <strong>無料</strong>
                                        <p>容量 : 5MBまで </p>
                                    </div>
                                    <div class="card-footer">
                                        <button class="btn btn-primary purchase" disabled="true" data-id="1">購入</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="card shadow">
                                    <div class="card-header">
                                        <span>パッケージ2</span>
                                    </div>
                                    <div class="card-body">
                                        <strong>100</strong><small>￥/月</small>
                                        <p>容量 : 5GBまで </p>
                                    </div>
                                    <div class="card-footer">
                                        <button class="btn btn-primary purchase" data-id="2">購入</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block scripts %}
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{% static 'designs/js/main.js' %}"></script>
{% endblock %}

dashboard/templates/dashboard/payment_cancelled.html
{% extends 'designs/base.html' %}
{% load static %}
{% block links %}
{% endblock %}
{% block content %}
    <div id="content" class="container-fluid auth-wrapper full-height">
        <div class="row flex-1">
             <div class="col-lg-6 col-md-12 justify-content-center auth-panel">
                    <h3 class="text-danger" style="text-align: center;">支払い要請が取り消されました。</h3>
             </div>
        </div>

    </div>
{% endblock content %}
{% block scripts %}
{% endblock %}

dashboard/templates/dashboard/payment_history.html
{% extends 'designs/base.html' %}
{% block content %}
{% load static %}
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    </br>
    </br>
        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:homepage' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:userreject' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>ユーザー登録拒否</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">

        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:volumn' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>容量管理</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'dashboard:payment_history' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Payment History</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
    </ul>
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Begin Page Content -->
            <div class="container-fluid">
                <!-- Content Row -->
                <div class="row">
                    <div class=" col-xl-12 col-lg-12">
                        <div class="card shadow">
                        <table >
                            <thead class="card-header py-3">
                                <th>Created</th>
                                <th>User</th>
                                <th>Storage</th>
                                <th>Price</th>
                            </thead>
                            <tbody>
                                {% for payment in payment_history %}
                                <tr>
                                    <td>{{ payment.created }}</td>
                                    <td>{{ payment.user.username }}</td>
                                    <td>{{ payment.storage }}</td>
                                    <td>
                                        {% if payment.price == 0 %}
                                            Free
                                        {% else %}
                                            ¥{{ payment.price }}
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block scripts %}
{% endblock %}

dashboard/templates/dashboard/payment_success.html
{% extends 'designs/base.html' %}
{% load static %}
{% block links %}
{% endblock %}
{% block content %}
    <div id="content" class="container-fluid auth-wrapper full-height">
        <div class="row flex-1">
             <div class="col-lg-4 col-md-12 justify-content-center auth-panel">
                    <div class="card shadow">
                        <div class="card-header">
                            <h4>お支払い申請に成功しました。</h4>
                        </div>
                        <div class="card-body">
                            <p class="text-success">お客様は{{ file_space }}Bytes購入に成功しました。<a href="/">こちらへ</a></p>
                        </div>
                    </div>

             </div>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
{% endblock %}

dashboard/templates/dashboard/userreject.html
{% extends 'designs/base.html' %}
{% block content %}
{% load static %}
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    </br>
    </br>
        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:homepage' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'dashboard:userreject' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>ユーザー登録拒否</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">

        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:volumn' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>容量管理</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:payment_history' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Payment History</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
    </ul>
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Begin Page Content -->
            <div class="container-fluid">
                <!-- Content Row -->
                <div class="row">
                    <div class=" col-xl-7 col-lg-7">
                        <div class="card shadow">
                        <table >
                            <thead class="card-header py-3">
                                <th>No</th>
                                <th>メールアドレス</th>
                                <th>デート</th>
                                <th></th>
                            </thead>
                            <tbody>
                                {% for reject in RejectUser %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ reject.email }}</td>
                                    <td>{{ reject.applied }}</td>
                                    <td style="text-align: right;"><button type="submit" data-id="{{ reject.id }}" class="btn btn-primary reuser_delete"><span class="icon text-blue-50"><i class="fa fa-remove"></i></span></button></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        </div>
                    </div>

                    <div class=" col-xl-5 col-lg-5">
                        <div class="card shadow">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-2">登録拒否ユーザー追加</h1>
                                </div>
                                <form class="user" action="{% url 'dashboard:add_userreject' %}" method="POST">
                                    <div class="form-group">
                                        {% csrf_token %}
                                        <input type="email" name="email" class="form-control form-control-user" placeholder="メールアドレス">
                                    </div>
                                    <div style="text-align: center;">
                                        <input class="btn btn-primary" type="submit" value="追加" />
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block scripts %}
<script>
    $(document).ready(function(){
        var csrftoken = "{{ csrf_token }}";
       
        $('body').on('click', '.reuser_delete', function(){
            var r = confirm("本当に削除しますか？");
            if(r == true){
                var $this = $(this);
                var id = $(this).data('id');
                $.ajax({
                    url: "{% url 'dashboard:delete_userreject' %}",
                    type:'POST',
                    data:{
                        id:id,                    
                        csrfmiddlewaretoken:csrftoken
                    },
                    success: function (data) {
                                        
                        $this.closest('tr').remove();
                        //alert("成功しました。"); 
                    }
                })
            }
            else{
                showToast("いいえ。","red");
            }
        })
        
    })
</script>
{% endblock %}

dashboard/templates/dashboard/volumn.html
{% extends 'designs/base.html' %}
{% block content %}
{% load static %}
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    </br>
    </br>
        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:homepage' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <li class="nav-item ">
            <a class="nav-link" href="{% url 'dashboard:userreject' %}">
                <i class="fas fa-fw fa-cog"></i>
                <span>ユーザー登録拒否</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'dashboard:volumn' %}">
                <i class="fas fa-fw fa-wrench"></i>
                <span>容量管理</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:payment_history' %}">
                <i class="fas fa-fw fa-chart-area"></i>
                <span>ペイメントヒストリー</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
    </ul>
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Begin Page Content -->
            <div class="container-fluid">
                <!-- Content Row -->
                <div class="row">
                    <div class=" col-xl-12 col-lg-12">
                        <div class="card shadow">
                        <table id="usertable">
                            <thead class="card-header py-3">
                                <th>No</th>
                                <th>ールアドレス</th>
                                <th>サイズ</th>
                                <!--<th style="text-align: right;">変更</th>-->
                            </thead>
                            <tbody>
                                {% for user in users %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ user.email }}</td>
                                    <td><select class="filesize" data-profile-id="{{ user.profile.id }}">
                                            <option value="{{ user.profile.file_size }}" selected>{% widthratio user.profile.file_size 1048576 1 %}MB以下</option>
                                            <option value="5242880">5MB以下</option>
                                            <option value="10485760">10MB以下</option>
                                            <option value="104857600">100MB以下</option>
                                            <option value="1048576000">1024MB以下</option>
                                        </select>
                                    </td>
                                    <!--<td style="text-align: right;"><button class="btn btn-primary updatefilesize" type="submit"><span class="icon text-blue-50"><i class="fa fa-edit"></i></span></button></td>-->
                                    <input type="hidden" class='profile_id' value="{{ user.profile.id }}">
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        </div>
                    </div>

                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% block scripts %}
    <script>
        $(document).ready(function(){
            $('#usertable').on('change','.filesize',function(){
                //var currentRow = $(this).closest("tr");
                //var profile_id = currentRow.find(".profile_id").val();
                //var file_size = currentRow.find(".filesize").val();
                
                var profile_id = $(this).data('profile-id');
                var file_size = $(this).val();

                var csrftoken = "{{ csrf_token }}";
                var r = confirm("ファイルサイズを変更しますか？");
                if(r == true){
                    console.log(profile_id,file_size);
                    $.ajax({
                        url: '{% url 'dashboard:save_filesizeupdate' %}',
                        type:'POST',
                        data:{
                            profile_id:profile_id,
                            file_size:file_size,
                            csrfmiddlewaretoken:csrftoken
                        },
                        success: function (data) {
                            console.log(data);
                            showToast("変更に成功しました。","green");
                        }
                    })
                }else{
                    showToast("変更をキャンセルしました。","red");
                }
            })
        })
    </script>
    
{% endblock %}