dashboard/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import include
from django.views.generic import TemplateView
from .views.user import (DashboardView, userreject, SignUp, ProfileUpdateView, PasswordUpdateView, ProjectDeleteView,DashboardInfiniteScroll,
                        get_acquaintances, filesizeupdate, save_filesizeupdate, add_userreject, delete_userreject,upload_files,set_zipfile_name,get_batch,get_files_as_zip,get_remaining_space,payment,stripe_config,create_checkout_session,stripe_webhook,SuccessView,CancelledView,payment_history)
from .forms import ProfiledAuthenticationForm,PasswordResetFormUpdate
from django.urls import reverse_lazy

app_name = "dashboard"

urlpatterns = [
    # path('', TemplateView.as_view(template_name="dashboard/home.html"), name="homepage"),
    path('',DashboardView.as_view(), name="homepage"),
    path('home/infinite-scroll/',DashboardInfiniteScroll.as_view(), name="dashboardInfiniteScroll"),  
    path('userreject/', userreject, name="userreject"),
    path('add_userreject/', add_userreject, name="add_userreject"),
    path('delete_userreject/', delete_userreject, name="delete_userreject"),
    path('volumn/', filesizeupdate, name='volumn'),
    path('update_file_size', save_filesizeupdate, name="save_filesizeupdate"),
    path('upload_files',upload_files,name='upload_files'),
    path('set_zipfile_name',set_zipfile_name,name='set_zipfile_name'),
    path('payment',payment,name='payment'),
    path('payment_history',payment_history,name='payment_history'),

    # payment
    path('config/', stripe_config,name='config'),
    path('create-checkout-session/',create_checkout_session),
    path('payment/success/', SuccessView.as_view()),
    path('payment/cancelled/', CancelledView.as_view()),
    path('payment/webhook/', stripe_webhook),

    path('login/', auth_views.LoginView.as_view(form_class=ProfiledAuthenticationForm, redirect_authenticated_user=True), name="login"),
    path('signup/', SignUp.as_view(), name="signup"),
    path('password_change/', PasswordUpdateView.as_view(), name='password_change'),
    path('password-reset/',auth_views.PasswordResetView.as_view(form_class=PasswordResetFormUpdate,success_url=reverse_lazy('dashboard:password_reset_done')),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('dashboard:password_reset_complete')),name='password_reset_confirm'),
    path('password-reset/complete/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name="profile"),

    path('acquaintances/', get_acquaintances, name="acquaintances"),
    path('project/<int:project_id>/delete', ProjectDeleteView.as_view(), name="projectDelete"),
    # path('', include('django.contrib.auth.urls'))
    path('<uuid:batch_id>',get_batch,name='get_batch'),
    path('get_files_as_zip',get_files_as_zip,name='get_files_as_zip'),
    path('get_remaining_space',get_remaining_space,name='get_remaining_space'),
]

designs/urls.py
from django.urls import path

from . import views
from .views import uploadDesign
app_name = 'designs'

urlpatterns = [

    path('', views.index, name='index'),
    path('upload', views.uploadDesign, name='uploadDesign')  

]

techup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from decorator_include import decorator_include
from django.contrib.auth.decorators import login_required


urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('designs/', decorator_include([login_required], ('designs.urls', 'designs'))),
    path('', include('dashboard.urls'))
]

if not settings.PRODUCTION:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

designs/models.py
from django.db import models
import uuid
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.db.models import Count
import mimetypes
# Create your models here.

class Design(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.OneToOneField("dashboard.Project", on_delete=models.CASCADE)
    pub_date = models.DateTimeField(_("Date published"),editable=False, auto_now_add=True)
    due_date = models.DateField(_("Date needed by"),null=True,blank=True,default=None)
    description = models.TextField(_("Design description"),default=None,null=True,blank=True)
    last_updated = models.DateTimeField(_("Last updated"), editable=False, auto_now=True)

    def __str__(self):
        return self.project.title

    @property
    def last_version(self):
        return self.versiongroup_set.count()
    
    @property
    def latest_version(self):
        return self.versiongroup_set.annotate(version_count=Count("version")).filter(version_count__gt=0).first()

    @property
    def imageset(self):
        return [i for i in self.designfile_set.all() if i.content_type and "image/" in i.content_type]

    @property
    def fileset(self):
        return [i for i in self.designfile_set.all() if not i.content_type or not "image/" in i.content_type]

    @property
    def no_of_files(self):
        return self.designfile_set.count()

    
    def delete(self, *args, **kwargs):
        if not hasattr(self.project, 'ticket'):
            self.project.delete()
        super(Design, self).delete(*args, **kwargs)

class DesignFile(models.Model):
    file = models.FileField(upload_to="design_assets")
    filename = models.CharField(_("Original filename"), max_length=1000)
    design = models.ForeignKey(Design, on_delete=models.CASCADE)

    @property
    def content_type(self):
        return mimetypes.guess_type(self.filename, strict=True)[0]

    @property
    def file_size(self):
        return (self.file.size/1000000)

class VersionGroupManager(models.Manager):
    def get_queryset(self):
        return super(VersionGroupManager, self).get_queryset().annotate(version_count=Count("version")).filter(version_count__gt=0)

class VersionGroup(models.Model):
    class Meta:
        ordering = ['-version_no']
    design = models.ForeignKey(Design, on_delete=models.CASCADE)
    version_no = models.IntegerField(_("Version #"), editable=False)
    pub_date = models.DateTimeField(_("Date uploaded"),editable=False, auto_now_add=True)
    objects = VersionGroupManager()

    def __str__(self):
        return f"{self.design.project.title} : VersionGroup {self.version_no }"

    def increment_version_number(self):
        last_version = self.design.versiongroup_set.first()
        if not last_version:
            return 1
        version_no = last_version.version_no
        new_version_no = version_no + 1
        return new_version_no

    def save(self, *args, **kwargs):
        if self.version_no is None:
            self.version_no = self.increment_version_number()
        super(VersionGroup, self).save(*args, **kwargs)    

class Version(models.Model):
    class Meta:
        ordering = ['version_label']
    version_group = models.ForeignKey(VersionGroup, on_delete=models.CASCADE)
    version_label = models.CharField(_("Version Label"), max_length=256, blank=True)
    asset = models.ImageField(_("Design Asset"), upload_to="design_assets")
    upload_date = models.DateTimeField(_("Date uploaded"),editable=False, auto_now_add=True)

    def __str__(self):
        return f"{self.version_group.design.project.title} : Version {self.version_group.version_no } {self.version_label}"

    def save(self, *args, **kwargs):
        if not self.version_label:
            self.version_label = self.increment_version_label()
        super(Version, self).save(*args, **kwargs)

    def increment_version_label(self):
        last_version = self.version_group.version_set.all().order_by('id').last()
        if not last_version:
            return "A"
        version_label = last_version.version_label
        new_version_label = chr(ord(version_label) + 1)
        return new_version_label

designs/forms.py
from django import forms
from .models import *

class DesignForm(forms.ModelForm):
    class Meta:
        model = Design
        fields = []

class ProjectDesignForm(forms.ModelForm):
    class Meta:
        model = Design
        fields = ['project']

class VersionGroupForm(forms.ModelForm):
    class Meta:
        model = VersionGroup
        fields = []

class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ['asset']

class UpdateVersionForm(forms.ModelForm):
    class Meta:
        model = VersionGroup
        fields = ['design']

designs/views.py
from django.shortcuts import render, Http404, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpResponseBadRequest
from django.views.decorators.http import require_POST
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .forms import DesignForm, VersionForm, VersionGroupForm, UpdateVersionForm
from .models import *
from designs.forms import ProjectDesignForm
from dashboard.forms import ProjectForm, ProjectAdminForm
from dashboard.models import Project
import json
from techup.utils import user_can_access
from django.core.exceptions import PermissionDenied

from django.http import JsonResponse, Http404

class JSONResponseMixin:
    def render_to_json_response(self, context, **response_kwargs):
        return JsonResponse(
            self.get_data(context),
            **response_kwargs
        )
    def get_data(self, context):
        """
        Returns an object that will be serialized as JSON by json.dumps().
        """
        return context

    def form_valid(self, form, comment=None, reply=None):
        if self.request.is_ajax():
            data = form.data.copy()
            

            print(data)
            return HttpResponse(json.dumps(data), content_type='application/json')
        return super(JSONResponseMixin, self).form_valid(form)

    def form_invalid(self, form):
        print("MIXIN FORM_INVALid")
        if self.request.is_ajax():
            return HttpResponse(json.dumps(form.errors), content_type='application/json', status=400)
        return super(JSONResponseMixin, self).form_valid(form)

# Create your views here.
def index(request):
    return render(request, 'designs/base.html', context={"project_form": ProjectAdminForm()})

@require_POST
def uploadDesign(request):
    is_admin = request.user.profile.is_admin
    is_staff = request.user.profile.is_staff
    design_form = DesignForm(request.POST)
    
    version_group_form = VersionGroupForm(request.POST)
    
    if is_admin or is_staff:
        project_form = ProjectAdminForm(request.POST)
    else:
        project_form = ProjectForm(request.POST)
    # Flow # 1: Direct design upload
    if design_form.is_valid() and version_group_form.is_valid() and project_form.is_valid() and request.FILES:
        # Create project
        project_form.instance.user = request.user
        if not is_admin | is_staff:
            project_form.instance.team = request.user.profile.team
        project = project_form.save()
        # Create design
        design_form.instance.project = project
        design = design_form.save()
        # Create Version Group
        version_group_form.instance.design = design
        version_group = version_group_form.save()
        # Create versions from files
        for file in request.FILES:
            file = request.FILES[file]
            version = Version(asset=file)
            version.version_group = version_group
            version.save()
        resp = HttpResponse(f'{{"message": "Uploaded successfully...", "id": "{design.id}"}}')
        resp.status_code = 200
    else:
        resp = HttpResponse(json.dumps(design_form.errors))
        resp.status_code = 400
    resp.content_type = "application/json"
    return resp

designs/templates/designs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>テックアップ</title>
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'designs/img/' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'designs/css/sb-admin-2.min.css' %}">
    <link rel="stylesheet" href="{% static 'designs/css/dropzone.css' %}">
    <link rel="stylesheet" href="{% static 'designs/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'designs/vendor/fontawesome-free/css/all.min.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gothic+A1|Helvetica|sans-serif" rel="stylesheet">
    <link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/start/jquery-ui.css"rel="stylesheet" />
    
    {% block links %}
    {% endblock %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145751270-2"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-145751270-2');
    </script>
    <script type="text/javascript">
        window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=document.createElement("script");r.type="text/javascript",r.async=!0,r.src="https://cdn.heapanalytics.com/js/heap-"+e+".js";var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(r,a);for(var n=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","resetIdentity","removeEventProperty","setEventProperties","track","unsetEventProperty"],o=0;o<p.length;o++)heap[p[o]]=n(p[o])};

          heap.load("2262313048");
    </script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'dashboard:homepage' %}">
            
            <div class="log-image">
                <img src="{% static 'designs/img/logo.png' %}" />
            </div>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarToggler">
            
            
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0 profile-toolbar">
                {% if user.is_authenticated %}               
                <li class="nav-item">
                    <!--<a class="nav-link dropdown-toggle profile" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                        
                        {% if request.user.profile.avatar %}
                            <img class="profile-image" src="{{ request.user.profile.avatar.url }}" />
                        {% else %}
                            <span class="profile-image" ></span>
                        {% endif %}
                        <span class="profile-name">{{ request.user.first_name }} {{ request.user.last_name }}</span>
                    </a>-->
                    
                    <a class="" href="{% url 'dashboard:logout' %}">ログアウト</a>
                   
                </li>
                
                {% else %}
                <li class="nav-item {% if '/' in request.path or '/signup' in request.path %}active{% endif %}"  >
                    <a class="nav-link" href="{% url 'dashboard:login' %}?next={{ request.path }}"><i class="fa fa-sign-in"></i> &nbsp;ログイン<span class="sr-only">(current)</span></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% if messages %}
    <div class="container messages justify-content-center">
        {% for message in messages %}
            {% if message.tags == "error" %}
            <div class="m-3 alert alert-danger alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!</strong> {{ message }}
            </div>
            {% else %}
            <div class="m-3 alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}{{ message.tags|title }}{% endif %}!</strong> {{ message }}
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}
    {% block content %}
        
    <div id="snackbar"></div>
    {% endblock content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block scripts %}
    <script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.2.2/dist/latest/bootstrap-autocomplete.min.js"></script>
    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function() {
          'use strict';
          window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
              form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                  event.preventDefault();
                  event.stopPropagation();
                }
                form.classList.add('was-validated');
              }, false);
            });
          }, false);
        })();

    </script>
    <script src="{% static 'designs/js/dropzone.js' %}"></script>
    <script type="text/javascript">
    function showToast(text, color) {
        if (color === "red") {
            color = "#dc3545";
        } else if (color === "green") {
            color = "#28a745";
        }
        // Get the snackbar DIV
        var x = document.getElementById("snackbar");
        // Add the "show" class to DIV
        x.style.backgroundColor = color;
        x.innerText = text;
        x.className = "show";
        // After 3 seconds, remove the show class from DIV
        setTimeout(function(){ x.className = x.className.replace("show", ""); }, 3000);
    }

       
    </script>
    {% endblock %}
    {% block extra_js %}
    {% endblock %}
    {% csrf_token %}
    <script>
        $('document').ready(function(){

            let csrftoken = $("[name=csrfmiddlewaretoken]").val();
            console.log(csrftoken)
            
        });
    </script>

<footer>
    <div class="row footer">
        <div class="col-md-8 footer-content-center">
            <div class="row">
            <div class="col-md-6 left">
                <p>企業紹介</p>
            </div>
            <div class="col-md-6 right">
                <p>お問い合わせ</p>
            </div>
            </div>
            </br>
            <p>Copyright Techup©  2021</p>
        </div>
    </div>
</footer>
</body>
</html>